spring.application.name=GYG_Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/gygdatabase
spring.datasource.username=postgres
spring.datasource.password=niceday27
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
